# .github/dependabot.yml
# Configuration for Dependabot automated dependency updates

version: 2
updates:

  # 1. Check for updates to Node.js dependencies using PNPM
  - package-ecosystem: "pnpm"
    directory: "/" # Run from the root, it will find all package.json files in the workspace
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "mauroociappinaph"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "mauroociappinaph"

  # 2. Check for updates to Python dependencies for ML services
  - package-ecosystem: "pip"
    directory: "/ml-services/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "mauroociappinaph"
    commit-message:
      prefix: "chore(deps-ml)"
      include: "scope"
    reviewers:
      - "mauroociappinaph"

  # 3. Check for updates to the GitHub Actions used in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "mauroociappinaph"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    reviewers:
      - "mauroociappinaph"